### ISSUE TITLE
USER STORY: Product Owner

### ISSUE THREAD

**Issue by qburn93** [qburn93/My-First-Agile-Project#7]
## Tasks
- [ ] In order to provide my opinion with regards to a certain running topic or event as a user, I can select and submit an answer from the poll
- [ ] In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.
- [ ] In order to provide additional thoughts beyond the response options as a user, I can add a comment before I submit my poll response.
- [ ] In order to collect users feedback, as an administrator, I can publish a poll
